### PR TITLE
Paper folder reorganization

### PR DESCRIPTION
**Pull request by stevenabreu7**
Clean up and reorganise the paper folder

### CODE REVIEW

**Comment by stevenabreu7** [comment]
I tried to go through your PR #87 @matjobst to make sure I didn't miss anything. Could you please double check that I got all the changes your requested? The naming is a bit different but probably doesn't matter too much, though feel free to suggest changes!

**Comment by matjobst** [comment]
Sure.
In the RNN directory, the spyx, norse, nengo and lava inference scripts are not renamed to a common scheme yet.
In the CNN, nengo and spyx don't follow the common scheme.

**Comment by VitF** [comment]
@matjobst what is the scheme to use? I'll do the renaming for the RNN folder accordingly.

**Comment by matjobst** [comment]
@VitF The others in the RNN start with Braille_inference_. It would be consistent if all use that scheme.

**Comment by VitF** [comment]
Ok, I thought you were referring to a common scheme across all the three experiment directories.

**Comment by VitF** [comment]
Now it should be ok. Could you @stevenabreu7 @matjobst please check?

**Comment by stevenabreu7** [comment]
LGTM!

**Pull request merged**
