### PR TITLE
Feature numpy tests

### PR DESCRIPTION
**Pull request by Jegp**
Addresses #21

### CODE REVIEW

**Comment by Jegp** [comment]
This is rebased on #19 and should not be merged before, btw

**Comment by matjobst** [comment]
The numpy changes are still missing in the read/write tests.

**Comment by biphasic** [comment]
> The numpy changes are still missing in the read/write tests.

where in [here](https://github.com/neuromorphs/NIR/blob/main/tests/test_readwrite.py) are there still torch tensors used?

**Comment by matjobst** [comment]
> > The numpy changes are still missing in the read/write tests.
> 
> where in [here](https://github.com/neuromorphs/NIR/blob/main/tests/test_readwrite.py) are there still torch tensors used?

I am not talking about torch tensors. But in NIR we basically said that we should use np.arrays for everything. Jens has already updated the tests in the test_nir to reflect that, but in test_readwrite there are still some python lists or scalar values used.

**Comment by Jegp** [comment]
Nicely caught @matjobst . And thanks for the review @biphasic!

**Pull request merged**
