### PR TITLE
Unified naming of paper experiments

### PR DESCRIPTION
**Pull request by matjobst**
This is a proposal to unify the naming of the files in the experiments for our paper.

There are still a few inconsistencies or unnecessary files (I would especially ask @stevenabreu7 to check these points):
- duplicates in the 03_rnn experiment:
  - Braille_inference_Rockpool.ipynb vs rockpool_inference.ipynb
  - Braille_inference_snntorch.ipynb vs snnTorch inference.ipynb
- debug or other files in the 03_rnn experiment - do we need all of them?
  - snntorch_debug_nirgraphs.ipynb
  - snntorch_debug.py
  - snnTorch save data.ipynb
  - snntorch save subtract.ipynb
  - snntorch_test_export.py
  - snntorch_test_import.py
  - Subgraph_rnn.ipynb
  - flatten_braille_graph.py
  - lava_analysis_simple.ipynb
  - lava_analysis_simple.py
  - lava_debug.py
  - lava__qat.py
  - lava_rnn.py
  - lava_analysis_simple.png
  - lava_inference_analysis.png
  - lava__qat_acc.png
  - lava__qat_loss.png
  - analyze_graph.py
  - 2311_norse_snntorch.ipynb

### CODE REVIEW

**Comment by bvogginger** [comment]
The following files in 03_RNN can be removed:

>       * flatten_braille_graph.py
>       * analyze_graph.py

I had created them and they are no longer needed.

**Comment by stevenabreu7** [comment]
Thanks for the PR @matjobst! I've actually already started that in the `rebuttal` branch, I will merge both our efforts into one later today.

**Comment by matjobst** [comment]
Oh, sorry, I missed that one. Thank you for your help! Should I close this PR then?

**Comment by stevenabreu7** [comment]
No worries at all, I forgot to open a PR for the branch I started but I didn't 🙈 I'll diff them later and merge mine into yours or yours into mine 🤗

**Comment by stevenabreu7** [comment]
Closing in favor of #88 (merged into main)

**Pull request closed without merging**
