### PR TITLE
Example/sinabs

### PR DESCRIPTION
**Pull request by sheiksadique**
Added a quick example in the docs for sinabs - nir interaction

### CODE REVIEW

**Comment by biphasic** [comment]
I've already done that here https://github.com/neuromorphs/NIR/tree/main/example/sinabs
I think such examples should only exist once and then be linked if necessary

**Comment by biphasic** [comment]
see also https://github.com/neuromorphs/NIR/issues/26

**Comment by sheiksadique** [comment]
@biphasic Yes I have seen this example and pretty much copy pasted it here. But this is not referenced in the documentation esp. in the structure that @Jegp has now added. What do you suggest we do for consistency?

**Comment by biphasic** [comment]
easiest way is to push a symlink. But actually if we integrate the examples in the documentation, we might be able to delete the top level examples

**Pull request merged**
